# Generated by Django 5.0.6 on 2024-07-26 20:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarifas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_id', models.CharField(default=api.models.crear_id, max_length=2, unique=True)),
                ('tarifa', models.FloatField()),
                ('categoria', models.CharField(max_length=20)),
                ('frecuencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('tarifa_id', models.IntegerField()),
            ],
        ),
    ]
