# Generated by Django 5.0.6 on 2024-07-26 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas',
            name='tarifa_id',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tarifa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tarifas', to_field='tarifa_id'),
        ),
    ]
