# Generated by Django 5.0.6 on 2024-07-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tarifas_tarifa_id_alter_vehiculo_tarifa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='anio',
            new_name='año',
        ),
    ]
