# Generated by Django 5.0.7 on 2024-07-25 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('categoria', models.CharField(max_length=30)),
                ('frecuencia', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('antiguedad', models.BigIntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
                ('tarifa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifas.tarifa')),
            ],
        ),
    ]
