# Generated by Django 5.0.7 on 2024-07-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='antiguedad',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
